{% set name = "dask-histogram" %}
{% set version = "2025.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dask_histogram/dask_histogram-{{ version }}.tar.gz
  sha256: ad59f787add2e280ccff409f36b8495d0a782689e6c9797b1d19fd95e3fde067

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.8.0
    - hatch-vcs
    - toml
  run:
    - python >={{ python_min }}
    - dask
    - dask-awkward >=2025
    - boost-histogram

test:
  requires:
    - python {{ python_min }}
  imports:
    - dask_histogram

about:
  home: https://dask-histogram.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Scale up histogramming with Dask.
  description: |
    Dask histogram extends the boost-histogram library to provide
    compatibility with Dask collections.
  doc_url: https://dask-histogram.readthedocs.io/
  dev_url: https://github.com/dask-contrib/dask-histogram/

extra:
  recipe-maintainers:
    - martindurant
    - jpivarski
    - lgray
    - douglasdavis
